version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - NAME_DB=hex
      - PASS_DB=HeX123@
    platform: linux/arm64/v8
    volumes:
      - ./.assets/conf/local/db:/docker-entrypoint-initdb.d/
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./.data:/var/lib/rabbitmq
      #platform: linux/arm64/v8
    networks:
      - backend

networks:
  backend: