CREATE TABLE accounts
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number  VARCHAR(15)                             NOT NULL,
    account_type    VARCHAR(15)                             NOT NULL,
    current_balance DECIMAL                                 NOT NULL,
    data_opened     date                                    NOT NULL,
    date_closed     date,
    account_status  VARCHAR(6)                              NOT NULL,
    customer_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_type VARCHAR(15)                             NOT NULL,
    person_id     BIGINT,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE persons
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name     VARCHAR(50)                             NOT NULL,
    last_name      VARCHAR(150)                            NOT NULL,
    date_of_birth  date                                    NOT NULL,
    email          VARCHAR(150)                            NOT NULL,
    phone_number   VARCHAR(15)                             NOT NULL,
    address        VARCHAR(150)                            NOT NULL,
    tax_identifier VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_persons PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_type VARCHAR(10)                             NOT NULL,
    amount           DECIMAL                                 NOT NULL,
    transaction_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    account_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE accounts
    ADD CONSTRAINT uc_accounts_accountnumber UNIQUE (account_number);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_CUSTOMERID FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE customers
    ADD CONSTRAINT FK_CUSTOMERS_ON_PERSON FOREIGN KEY (person_id) REFERENCES persons (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);